// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Changes.proto

package networking.protobuf;

public interface ChangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:networking.protobuf.ChangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp = 1;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
