// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Changes.proto

package networking.protobuf;

/**
 * Protobuf service {@code networking.protobuf.GossipService}
 */
public  abstract class GossipService
    implements com.google.protobuf.Service {
  protected GossipService() {}

  public interface Interface {
    /**
     * <code>rpc process(.networking.protobuf.ChangeRequest) returns (.networking.protobuf.ChangeAck);</code>
     */
    public abstract void process(
        com.google.protobuf.RpcController controller,
        networking.protobuf.ChangeRequest request,
        com.google.protobuf.RpcCallback<networking.protobuf.ChangeAck> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new GossipService() {
      @java.lang.Override
      public  void process(
          com.google.protobuf.RpcController controller,
          networking.protobuf.ChangeRequest request,
          com.google.protobuf.RpcCallback<networking.protobuf.ChangeAck> done) {
        impl.process(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.process(controller, (networking.protobuf.ChangeRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return networking.protobuf.ChangeRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return networking.protobuf.ChangeAck.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc process(.networking.protobuf.ChangeRequest) returns (.networking.protobuf.ChangeAck);</code>
   */
  public abstract void process(
      com.google.protobuf.RpcController controller,
      networking.protobuf.ChangeRequest request,
      com.google.protobuf.RpcCallback<networking.protobuf.ChangeAck> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return networking.protobuf.Changes.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.process(controller, (networking.protobuf.ChangeRequest)request,
          com.google.protobuf.RpcUtil.<networking.protobuf.ChangeAck>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return networking.protobuf.ChangeRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return networking.protobuf.ChangeAck.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends networking.protobuf.GossipService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void process(
        com.google.protobuf.RpcController controller,
        networking.protobuf.ChangeRequest request,
        com.google.protobuf.RpcCallback<networking.protobuf.ChangeAck> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        networking.protobuf.ChangeAck.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          networking.protobuf.ChangeAck.class,
          networking.protobuf.ChangeAck.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public networking.protobuf.ChangeAck process(
        com.google.protobuf.RpcController controller,
        networking.protobuf.ChangeRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public networking.protobuf.ChangeAck process(
        com.google.protobuf.RpcController controller,
        networking.protobuf.ChangeRequest request)
        throws com.google.protobuf.ServiceException {
      return (networking.protobuf.ChangeAck) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        networking.protobuf.ChangeAck.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:networking.protobuf.GossipService)
}

